vim.cmd([[iabbrev _cstrr const std::string&]])
vim.cmd([[iabbrev _cstr const std::string&]])
vim.cmd([[iabbrev _veci std::vector<int>]])
vim.cmd([[iabbrev _vecs std::vector<std::string>]])
vim.cmd([[iabbrev _ptr std::unique_ptr<>]])
vim.cmd([[iabbrev _shptr std::shared_ptr<>]])
vim.cmd([[iabbrev _fref float&]])
vim.cmd([[iabbrev _dref double&]])
